export interface AzureDeployment {
	active: boolean,
	author: string,
	author_email: string,
	complete: boolean,
	deployer: string,
	end_time: string,
	id: string,
	is_readonly: boolean,
	is_temp: boolean,
	last_success_end_time: string,
	log_url: string,
	message: string,
	progress: string,
	provisioningState: string,
	received_time: string,
	site_name: string,
	start_time: string,
	status: number,
	status_text: string,
	url: string,
}